### ISSUE TITLE
Reproducing results - reacher3d file?

### ISSUE THREAD

**Issue by jimzers** [natolambert/continuousprediction#14]
Hi there,

Was looking into the README.md file and noticed some instructions mentioning a "Reacher3d" mujoco model - is there a location where I can download such files?

Thanks!

**Comment by natolambert** [comment]
Hi Adam,

The raw xml for the reacher simulation is found in the envs tab, under assets (specifically, [here](https://github.com/natolambert/continuousprediction/blob/master/envs/assets/reacher3d.xml)).

Or, were you asking something different?

**Comment by jimzers** [comment]
Hey Nathan,

Thanks! Was looking for the mujoco file :)
